// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_shared();
Q_GHS_KEEP_REFERENCE(qml_register_types_shared)

class sharedPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    sharedPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_shared;
        Q_UNUSED(registration)
    }
};



#include "window_shared_sharedPlugin.moc"
